package ansi

type ANSIEscapeSequenceByte byte

const (
	ESCAPEByte ANSIEscapeSequenceByte = 0x1b
)

type ANSIEscapeSequence string

const (
	ESCAPE                        ANSIEscapeSequence = "\x1b"
	SS3                           ANSIEscapeSequence = ESCAPE + "O"
	CSI                           ANSIEscapeSequence = ESCAPE + "["
	RESET                         ANSIEscapeSequence = CSI + "0m"
	CLEAR_SCREEN                  ANSIEscapeSequence = CSI + "2J"
	CLEAR_SCROLLBACK              ANSIEscapeSequence = CSI + "3J"
	CURSOR_HOME                   ANSIEscapeSequence = CSI + "H"
	HIDE_CURSOR                   ANSIEscapeSequence = CSI + "?25l"
	SHOW_CURSOR                   ANSIEscapeSequence = CSI + "?25h"
	ENTER_ALTERNATE_SCREEN        ANSIEscapeSequence = CSI + "?1049h"
	EXIT_ALTERNATE_SCREEN         ANSIEscapeSequence = CSI + "?1049l"
	ENABLE_MOUSE_REPORTING        ANSIEscapeSequence = CSI + "?1000h"
	DISABLE_MOUSE_REPORTING       ANSIEscapeSequence = CSI + "?1000l"
	ENABLE_MOUSE_DRAG             ANSIEscapeSequence = CSI + "?1002h"
	DISABLE_MOUSE_DRAG            ANSIEscapeSequence = CSI + "?1002l"
	ENABLE_SGR_MOUSE              ANSIEscapeSequence = CSI + "?1006h"
	DISABLE_SGR_MOUSE             ANSIEscapeSequence = CSI + "?1006l"
	FG_BLACK                      ANSIEscapeSequence = CSI + "0;30m"
	FG_RED                        ANSIEscapeSequence = CSI + "0;31m"
	FG_GREEN                      ANSIEscapeSequence = CSI + "0;32m"
	FG_YELLOW                     ANSIEscapeSequence = CSI + "0;33m"
	FG_BLUE                       ANSIEscapeSequence = CSI + "0;34m"
	FG_PURPLE                     ANSIEscapeSequence = CSI + "0;35m"
	FG_CYAN                       ANSIEscapeSequence = CSI + "0;36m"
	FG_WHITE                      ANSIEscapeSequence = CSI + "0;37m"
	FG_BOLD_BLACK                 ANSIEscapeSequence = CSI + "1;30m"
	FG_BOLD_RED                   ANSIEscapeSequence = CSI + "1;31m"
	FG_BOLD_GREEN                 ANSIEscapeSequence = CSI + "1;32m"
	FG_BOLD_YELLOW                ANSIEscapeSequence = CSI + "1;33m"
	FG_BOLD_BLUE                  ANSIEscapeSequence = CSI + "1;34m"
	FG_BOLD_PURPLE                ANSIEscapeSequence = CSI + "1;35m"
	FG_BOLD_CYAN                  ANSIEscapeSequence = CSI + "1;36m"
	FG_BOLD_WHITE                 ANSIEscapeSequence = CSI + "1;37m"
	FG_UNDERLINE_BLACK            ANSIEscapeSequence = CSI + "4;30m"
	FG_UNDERLINE_RED              ANSIEscapeSequence = CSI + "4;31m"
	FG_UNDERLINE_GREEN            ANSIEscapeSequence = CSI + "4;32m"
	FG_UNDERLINE_YELLOW           ANSIEscapeSequence = CSI + "4;33m"
	FG_UNDERLINE_BLUE             ANSIEscapeSequence = CSI + "4;34m"
	FG_UNDERLINE_PURPLE           ANSIEscapeSequence = CSI + "4;35m"
	FG_UNDERLINE_CYAN             ANSIEscapeSequence = CSI + "4;36m"
	FG_UNDERLINE_WHITE            ANSIEscapeSequence = CSI + "4;37m"
	BG_BLACK                      ANSIEscapeSequence = CSI + "40m"
	BG_RED                        ANSIEscapeSequence = CSI + "41m"
	BG_GREEN                      ANSIEscapeSequence = CSI + "42m"
	BG_YELLOW                     ANSIEscapeSequence = CSI + "43m"
	BG_BLUE                       ANSIEscapeSequence = CSI + "44m"
	BG_PURPLE                     ANSIEscapeSequence = CSI + "45m"
	BG_CYAN                       ANSIEscapeSequence = CSI + "46m"
	BG_WHITE                      ANSIEscapeSequence = CSI + "47m"
	FG_HIGH_INTENSITY_BLACK       ANSIEscapeSequence = CSI + "0;90m"
	FG_HIGH_INTENSITY_RED         ANSIEscapeSequence = CSI + "0;91m"
	FG_HIGH_INTENSITY_GREEN       ANSIEscapeSequence = CSI + "0;92m"
	FG_HIGH_INTENSITY_YELLOW      ANSIEscapeSequence = CSI + "0;93m"
	FG_HIGH_INTENSITY_BLUE        ANSIEscapeSequence = CSI + "0;94m"
	FG_HIGH_INTENSITY_PURPLE      ANSIEscapeSequence = CSI + "0;95m"
	FG_HIGH_INTENSITY_CYAN        ANSIEscapeSequence = CSI + "0;96m"
	FG_HIGH_INTENSITY_WHITE       ANSIEscapeSequence = CSI + "0;97m"
	FG_BOLD_HIGH_INTENSITY_BLACK  ANSIEscapeSequence = CSI + "1;90m"
	FG_BOLD_HIGH_INTENSITY_RED    ANSIEscapeSequence = CSI + "1;91m"
	FG_BOLD_HIGH_INTENSITY_GREEN  ANSIEscapeSequence = CSI + "1;92m"
	FG_BOLD_HIGH_INTENSITY_YELLOW ANSIEscapeSequence = CSI + "1;93m"
	FG_BOLD_HIGH_INTENSITY_BLUE   ANSIEscapeSequence = CSI + "1;94m"
	FG_BOLD_HIGH_INTENSITY_PURPLE ANSIEscapeSequence = CSI + "1;95m"
	FG_BOLD_HIGH_INTENSITY_CYAN   ANSIEscapeSequence = CSI + "1;96m"
	FG_BOLD_HIGH_INTENSITY_WHITE  ANSIEscapeSequence = CSI + "1;97m"
	BG_HIGH_INTENSITY_BLACK       ANSIEscapeSequence = CSI + "0;100m"
	BG_HIGH_INTENSITY_RED         ANSIEscapeSequence = CSI + "0;101m"
	BG_HIGH_INTENSITY_GREEN       ANSIEscapeSequence = CSI + "0;102m"
	BG_HIGH_INTENSITY_YELLOW      ANSIEscapeSequence = CSI + "0;103m"
	BG_HIGH_INTENSITY_BLUE        ANSIEscapeSequence = CSI + "0;104m"
	BG_HIGH_INTENSITY_PURPLE      ANSIEscapeSequence = CSI + "0;105m"
	BG_HIGH_INTENSITY_CYAN        ANSIEscapeSequence = CSI + "0;106m"
	BG_HIGH_INTENSITY_WHITE       ANSIEscapeSequence = CSI + "0;107m"
)
