version: "2"

linters:
  default: standard
  enable:
    - cyclop
    - errname
    - errorlint
    - gocheckcompilerdirectives
    - gochecknoinits
    - gocognit
    - nestif
    - nilerr
    - nilnil
    - nolintlint

  settings:
    cyclop:
      max-complexity: 15
      package-average: 0.0
    gocognit:
      min-complexity: 30
    nestif:
      min-complexity: 4
    nolintlint:
      require-specific: true
      require-explanation: true
